openapi: 3.0.1
info:
  title: App-Service
  description: App Service API
  contact:
    name: Violet.io
    url: https://violet.io
  version: v1
servers:
- url: https://sandbox-api.violet.io/v1
tags:
- name: Apps
- name: Apps - Merchant Install
  description: Merchant/App Installs
- name: Apps - Merchant Install - Configuration
  description: Merchant/App Install Configuration Entities
- name: Developers - Metadata
  description: Developer metadata entities
- name: Apps - Merchant Install - Commission Rate
  description: Merchant/App Install commission rate entities
paths:
  /apps/{app_id}/merchants/uninstall:
    post:
      tags:
      - Apps - Merchant Install
      summary: App Request Merchant App Uninstall
      description: Send a request to uninstall (disconnect) a Merchant from the given
        App
      operationId: requestMerchantAppUninstall
      parameters:
      - name: X-Violet-Token
        in: header
        schema:
          type: string
      - name: X-Violet-App-Secret
        in: header
        schema:
          type: string
      - name: X-Violet-App-Id
        in: header
        schema:
          type: integer
          format: int32
      - name: app_id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UninstallAppRequest'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantAppInstall'
  /apps/{app_id}/webhooks/{webhook_id}/simulate:
    post:
      tags:
      - Apps
      summary: Simulate Webhook Event
      description: Simulates a webhook event for testing purposes. A webhook event
        will be created and delivered to the remote endpoint of the webhook.
      operationId: simulateWebhook
      parameters:
      - name: X-Violet-Token
        in: header
        schema:
          type: string
      - name: X-Violet-App-Secret
        in: header
        schema:
          type: string
      - name: X-Violet-App-Id
        in: header
        schema:
          type: integer
          format: int32
      - name: app_id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: webhook_id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimulateWebhookRequest'
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /apps/{app_id}/merchants/{merchant_id}/commission_rate:
    put:
      tags:
      - Apps - Merchant Install - Configuration
      summary: Set Merchant/Channel Commission Rate
      description: "Updates the Commission Rate for a specified Merchant's relationship\
        \ with a specified Channel. Commission Rate can be locked/unlocked by a Channel,\
        \ preventing changes by the Merchant."
      operationId: updateMerchantAppInstallCommissionRate
      parameters:
      - name: X-Violet-Token
        in: header
        schema:
          type: string
      - name: X-Violet-App-Secret
        in: header
        schema:
          type: string
      - name: X-Violet-App-Id
        in: header
        schema:
          type: integer
          format: int32
      - name: app_id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: merchant_id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MerchantAppInstallCommissionRateRequest'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantAppInstall'
  /apps/merchants/{merchant_id}/configuration/new_offer_auto_subscribe/enabled:
    get:
      operationId: getEnabledNewOfferAutoSubscribeAppIdsByMerchantId
      parameters:
      - name: X-Violet-Token
        in: header
        schema:
          type: string
      - name: X-Violet-App-Secret
        in: header
        schema:
          type: string
      - name: X-Violet-App-Id
        in: header
        schema:
          type: integer
          format: int32
      - name: merchant_id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  type: integer
                  format: int32
  /apps/commission_rate/change_log:
    get:
      tags:
      - Apps - Merchant Install - Commission Rate
      summary: Search All Commission Rates Change Log
      operationId: getAllMerchantAppInstallCommissionRateChangeLog
      parameters:
      - name: X-Violet-Token
        in: header
        schema:
          type: string
      - name: X-Violet-App-Secret
        in: header
        schema:
          type: string
      - name: X-Violet-App-Id
        in: header
        schema:
          type: integer
          format: int32
      - name: app_id
        in: query
        schema:
          type: integer
          format: int32
      - name: merchant_id
        in: query
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        schema:
          type: integer
          format: int32
          default: 1
      - name: size
        in: query
        schema:
          type: integer
          format: int32
          default: 20
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageMerchantAppInstallCommissionRateChangeWithAppNameAndMerchantName'
components:
  schemas:
    MerchantAppInstall:
      required:
      - app_id
      - merchant_id
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        app_id:
          type: integer
          description: App ID
          format: int32
        merchant_id:
          type: integer
          description: Merchant ID
          format: int32
        scope:
          type: string
          description: Scope
        status:
          type: string
          description: Status
          enum:
          - REQUESTED
          - CONNECTED
          - NOT_CONNECTED
          - DECLINED
        install_source:
          type: string
          description: Source of the App Install
          enum:
          - DIRECT
          - CATEGORY
          - APP_AGREEMENT
        commission_rate:
          type: number
          description: Custom commission rate between the channel and supplier.
          format: double
        commission_locked:
          type: boolean
          description: Indicates if the commission rate is locked or not. Commission
            rates can only be locked or unlocked by a Channel.
        date_created:
          type: string
          description: Date of creation
          format: date-time
          readOnly: true
        date_last_modified:
          type: string
          description: Date of last update
          format: date-time
          readOnly: true
      description: Record of Application Install by a Merchant
    UninstallAppRequest:
      required:
      - merchant_id
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        app_id:
          type: integer
          description: ID of the App to uninstall from
          format: int32
        merchant_id:
          type: integer
          description: ID of Merchant being uninstalled
          format: int32
      description: A Request to uninstall/disconnect a merchant from an app
    SimulateWebhookRequest:
      type: object
      properties:
        order_id:
          type: integer
          description: Order ID to be used on simulation
          format: int64
        offer_id:
          type: integer
          description: Offer ID to be used on simulation
          format: int64
        collection_id:
          type: integer
          description: Collection ID to be used on simulation
          format: int64
        merchant_id:
          type: integer
          description: Merchant ID to be used on simulation
          format: int32
      description: Request body for webhook simulator
    MerchantAppInstallCommissionRateRequest:
      type: object
      properties:
        commission_rate:
          type: number
          description: Custom commission rate between the channel and supplier.
          format: double
        commission_locked:
          type: boolean
          description: Indicates if the commission rate is locked or not. Commission
            rates can only be locked or unlocked by a Channel.
    MerchantAppInstallCommissionRateChange:
      type: object
      properties:
        commission_rate:
          type: number
          description: The commission rate of the merchant app install
          format: double
        commission_locked:
          type: boolean
          description: Indicates if the commission rate was locked or not. Commission
            rates can only be locked or unlocked by a Channel.
        user_id:
          type: integer
          description: The user id that updated the merchant app install commission
            rate
          format: int64
        user_type:
          type: string
          description: The user type that updated the merchant app install commission
            rate
          enum:
          - SUPER_ADMIN
          - ADMIN
          - MERCHANT
          - USER
          - DEVELOPER
          - INFLUENCER
          - HYBRID
          - OTHER
        date_created:
          type: string
          description: Date of creation
          format: date-time
      description: Merchant app install commission rate change log
    MerchantAppInstallCommissionRateChangeWithAppNameAndMerchantName:
      type: object
      properties:
        MerchantAppInstallCommissionRateChange:
          $ref: '#/components/schemas/MerchantAppInstallCommissionRateChange'
        appId:
          type: integer
          description: The app id tied to the merchant app install record
          format: int32
        appName:
          type: string
          description: Name of the app tied to the merchant app install record
        merchantId:
          type: integer
          description: The merchant id tied to the merchant app install record
          format: int32
        merchantName:
          type: string
          description: Name of the merchant tied to the merchant app install record
        prevRate:
          type: number
          description: The previous commission rate value applied to the merchant
            app install
          format: double
      description: A MerchantAppInstallCommissionRateChange with the relevant app
        and merchant identification
    PageMerchantAppInstallCommissionRateChangeWithAppNameAndMerchantName:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        first:
          type: boolean
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/MerchantAppInstallCommissionRateChangeWithAppNameAndMerchantName'
        number:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/Sort'
        numberOfElements:
          type: integer
          format: int32
        pageable:
          $ref: '#/components/schemas/Pageable'
        last:
          type: boolean
        empty:
          type: boolean
    Pageable:
      type: object
      properties:
        offset:
          type: integer
          format: int64
        sort:
          $ref: '#/components/schemas/Sort'
        paged:
          type: boolean
        unpaged:
          type: boolean
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
    Sort:
      type: object
      properties:
        empty:
          type: boolean
        sorted:
          type: boolean
        unsorted:
          type: boolean
