---
swagger: "2.0"
info:
  description: "User Service API"
  version: "v1"
  title: "User-Service"
  contact:
    name: "Violet.io"
    url: "https://violet.io"
host: "sandbox-api.violet.io"
basePath: "/v1"
tags:
- name: "Access"
  description: ""
- name: "Orgs"
  description: "Org related entities"
- name: "Users"
  description: "User related entities"
schemes:
- "https"
paths:
  /auth/token:
    get:
      tags:
      - "Access"
      summary: "Refresh Token"
      description: ""
      operationId: "refreshToken"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "X-Violet-Token"
        in: "header"
        required: false
        type: "string"
      - name: "X-Violet-App-Secret"
        in: "header"
        required: false
        type: "string"
      - name: "X-Violet-App-Id"
        in: "header"
        required: false
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/RefreshTokenResponse"
  /login:
    post:
      tags:
      - "Access"
      summary: "Login"
      description: ""
      operationId: "login"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "X-Violet-App-Secret"
        in: "header"
        required: false
        type: "string"
      - name: "X-Violet-App-Id"
        in: "header"
        required: false
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/LoginResponse"
definitions:
  LoginResponse:
    type: "object"
    required:
    - "email"
    - "first_name"
    - "last_name"
    - "password"
    - "type"
    properties:
      id:
        type: "integer"
        format: "int64"
        readOnly: true
      first_name:
        type: "string"
        description: "The users first name"
      last_name:
        type: "string"
        description: "The users last name"
      password:
        type: "string"
        description: "The users raw desired password"
      email:
        type: "string"
        description: "The users unique email address"
      type:
        type: "string"
        description: "The allowed values for the user type"
        enum:
        - "ADMIN"
        - "MERCHANT"
        - "USER"
        - "DEVELOPER"
        - "INFLUENCER"
      verified:
        type: "boolean"
        description: "If a user has verified their emailed address"
        enum:
        - true
        - false
      status:
        type: "string"
        description: "The status of the user"
        enum:
        - "INACTIVE"
        - "ACTIVE"
        - "DISABLED"
      date_created:
        type: "string"
        format: "date-time"
        description: "Date of creation"
      date_last_modified:
        type: "string"
        format: "date-time"
        description: "Date of last update"
      roles:
        type: "array"
        uniqueItems: true
        items:
          $ref: "#/definitions/Role"
      tos_accepted:
        type: "boolean"
        description: "Terms of Service Accepted"
      payment_configured:
        type: "boolean"
        description: "Is the Users Payment Settings Configured"
      privacy_policy_accepted:
        type: "boolean"
        description: "Privacy Policy Accepted"
      country_code:
        type: "string"
        description: "Country Code"
        enum:
        - "US"
        - "AU"
        - "AT"
        - "BE"
        - "CA"
        - "DK"
        - "FI"
        - "FR"
        - "DE"
        - "HK"
        - "IE"
        - "IT"
        - "JP"
        - "LU"
        - "MX"
        - "NL"
        - "NZ"
        - "NO"
        - "PT"
        - "SG"
        - "ES"
        - "SE"
        - "CH"
        - "GB"
        - "AF"
        - "AX"
        - "AL"
        - "DZ"
        - "AS"
        - "AD"
        - "AO"
        - "AI"
        - "AQ"
        - "AG"
        - "AR"
        - "AM"
        - "AW"
        - "AZ"
        - "BS"
        - "BH"
        - "BD"
        - "BB"
        - "BY"
        - "BZ"
        - "BJ"
        - "BM"
        - "BT"
        - "BO"
        - "BA"
        - "BW"
        - "BV"
        - "BR"
        - "IO"
        - "BN"
        - "BG"
        - "BF"
        - "BI"
        - "KH"
        - "CM"
        - "CV"
        - "KY"
        - "CF"
        - "TD"
        - "CL"
        - "CN"
        - "CX"
        - "CC"
        - "CO"
        - "KM"
        - "CG"
        - "CD"
        - "CK"
        - "CR"
        - "CI"
        - "HR"
        - "CU"
        - "CY"
        - "CZ"
        - "DJ"
        - "DM"
        - "DO"
        - "EC"
        - "EG"
        - "SV"
        - "GQ"
        - "ER"
        - "EE"
        - "ET"
        - "FK"
        - "FO"
        - "FJ"
        - "GF"
        - "PF"
        - "TF"
        - "GA"
        - "GM"
        - "GE"
        - "GH"
        - "GI"
        - "GR"
        - "GL"
        - "GD"
        - "GP"
        - "GU"
        - "GT"
        - "GG"
        - "GN"
        - "GW"
        - "GY"
        - "HT"
        - "HM"
        - "VA"
        - "HN"
        - "HU"
        - "IS"
        - "IN"
        - "ID"
        - "IR"
        - "IQ"
        - "IM"
        - "IL"
        - "JM"
        - "JE"
        - "JO"
        - "KZ"
        - "KE"
        - "KI"
        - "KP"
        - "KR"
        - "KW"
        - "KG"
        - "LA"
        - "LV"
        - "LB"
        - "LS"
        - "LR"
        - "LY"
        - "LI"
        - "LT"
        - "MO"
        - "MK"
        - "MG"
        - "MW"
        - "MY"
        - "MV"
        - "ML"
        - "MT"
        - "MH"
        - "MQ"
        - "MR"
        - "MU"
        - "YT"
        - "FM"
        - "MD"
        - "MC"
        - "MN"
        - "ME"
        - "MS"
        - "MA"
        - "MZ"
        - "MM"
        - "NA"
        - "NR"
        - "NP"
        - "AN"
        - "NC"
        - "NI"
        - "NE"
        - "NG"
        - "NU"
        - "NF"
        - "MP"
        - "OM"
        - "PK"
        - "PW"
        - "PS"
        - "PA"
        - "PG"
        - "PY"
        - "PE"
        - "PH"
        - "PN"
        - "PL"
        - "PR"
        - "QA"
        - "RE"
        - "RO"
        - "RU"
        - "RW"
        - "SH"
        - "KN"
        - "LC"
        - "PM"
        - "VC"
        - "WS"
        - "SM"
        - "ST"
        - "SA"
        - "SN"
        - "RS"
        - "SC"
        - "SL"
        - "SK"
        - "SI"
        - "SB"
        - "SO"
        - "ZA"
        - "GS"
        - "LK"
        - "SD"
        - "SR"
        - "SJ"
        - "SZ"
        - "SY"
        - "TW"
        - "TJ"
        - "TZ"
        - "TH"
        - "TL"
        - "TG"
        - "TK"
        - "TO"
        - "TT"
        - "TN"
        - "TR"
        - "TM"
        - "TC"
        - "TV"
        - "UG"
        - "UA"
        - "AE"
        - "UM"
        - "UY"
        - "UZ"
        - "VU"
        - "VE"
        - "VN"
        - "VG"
        - "VI"
        - "WF"
        - "EH"
        - "YE"
        - "ZM"
        - "ZW"
      token:
        type: "string"
        description: "Token"
      refresh_token:
        type: "string"
        description: "Refresh Token"
      merchant_id:
        type: "integer"
        format: "int32"
        description: "Merchant ID"
      merchant_ids:
        type: "array"
        description: "Merchant IDs"
        items:
          type: "integer"
          format: "int32"
      store_url:
        type: "string"
        description: "Store Url"
    description: "Login Response"
  Permission:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
        description: "Name of the Permission"
        minLength: 1
        maxLength: 50
      description:
        type: "string"
        description: "Brief description of the Permission"
        minLength: 0
        maxLength: 255
  RefreshTokenResponse:
    type: "object"
    required:
    - "token"
    properties:
      token:
        type: "string"
        description: "Token"
    description: "Refresh Token Response"
  Role:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
        description: "Name of the Role"
        minLength: 1
        maxLength: 50
      permissions:
        type: "array"
        description: "Permissions available to this Role"
        uniqueItems: true
        items:
          $ref: "#/definitions/Permission"
  User:
    type: "object"
    required:
    - "email"
    - "first_name"
    - "last_name"
    - "password"
    - "type"
    properties:
      id:
        type: "integer"
        format: "int64"
        readOnly: true
      first_name:
        type: "string"
        description: "The users first name"
      last_name:
        type: "string"
        description: "The users last name"
      password:
        type: "string"
        description: "The users raw desired password"
      email:
        type: "string"
        description: "The users unique email address"
      type:
        type: "string"
        description: "The allowed values for the user type"
        enum:
        - "ADMIN"
        - "MERCHANT"
        - "USER"
        - "DEVELOPER"
        - "INFLUENCER"
      verified:
        type: "boolean"
        description: "If a user has verified their emailed address"
        enum:
        - true
        - false
      status:
        type: "string"
        description: "The status of the user"
        enum:
        - "INACTIVE"
        - "ACTIVE"
        - "DISABLED"
      date_created:
        type: "string"
        format: "date-time"
        description: "Date of creation"
      date_last_modified:
        type: "string"
        format: "date-time"
        description: "Date of last update"
      roles:
        type: "array"
        uniqueItems: true
        items:
          $ref: "#/definitions/Role"
      tos_accepted:
        type: "boolean"
        description: "Terms of Service Accepted"
      payment_configured:
        type: "boolean"
        description: "Is the Users Payment Settings Configured"
      privacy_policy_accepted:
        type: "boolean"
        description: "Privacy Policy Accepted"
      country_code:
        type: "string"
        description: "Country Code"
        enum:
        - "US"
        - "AU"
        - "AT"
        - "BE"
        - "CA"
        - "DK"
        - "FI"
        - "FR"
        - "DE"
        - "HK"
        - "IE"
        - "IT"
        - "JP"
        - "LU"
        - "MX"
        - "NL"
        - "NZ"
        - "NO"
        - "PT"
        - "SG"
        - "ES"
        - "SE"
        - "CH"
        - "GB"
        - "AF"
        - "AX"
        - "AL"
        - "DZ"
        - "AS"
        - "AD"
        - "AO"
        - "AI"
        - "AQ"
        - "AG"
        - "AR"
        - "AM"
        - "AW"
        - "AZ"
        - "BS"
        - "BH"
        - "BD"
        - "BB"
        - "BY"
        - "BZ"
        - "BJ"
        - "BM"
        - "BT"
        - "BO"
        - "BA"
        - "BW"
        - "BV"
        - "BR"
        - "IO"
        - "BN"
        - "BG"
        - "BF"
        - "BI"
        - "KH"
        - "CM"
        - "CV"
        - "KY"
        - "CF"
        - "TD"
        - "CL"
        - "CN"
        - "CX"
        - "CC"
        - "CO"
        - "KM"
        - "CG"
        - "CD"
        - "CK"
        - "CR"
        - "CI"
        - "HR"
        - "CU"
        - "CY"
        - "CZ"
        - "DJ"
        - "DM"
        - "DO"
        - "EC"
        - "EG"
        - "SV"
        - "GQ"
        - "ER"
        - "EE"
        - "ET"
        - "FK"
        - "FO"
        - "FJ"
        - "GF"
        - "PF"
        - "TF"
        - "GA"
        - "GM"
        - "GE"
        - "GH"
        - "GI"
        - "GR"
        - "GL"
        - "GD"
        - "GP"
        - "GU"
        - "GT"
        - "GG"
        - "GN"
        - "GW"
        - "GY"
        - "HT"
        - "HM"
        - "VA"
        - "HN"
        - "HU"
        - "IS"
        - "IN"
        - "ID"
        - "IR"
        - "IQ"
        - "IM"
        - "IL"
        - "JM"
        - "JE"
        - "JO"
        - "KZ"
        - "KE"
        - "KI"
        - "KP"
        - "KR"
        - "KW"
        - "KG"
        - "LA"
        - "LV"
        - "LB"
        - "LS"
        - "LR"
        - "LY"
        - "LI"
        - "LT"
        - "MO"
        - "MK"
        - "MG"
        - "MW"
        - "MY"
        - "MV"
        - "ML"
        - "MT"
        - "MH"
        - "MQ"
        - "MR"
        - "MU"
        - "YT"
        - "FM"
        - "MD"
        - "MC"
        - "MN"
        - "ME"
        - "MS"
        - "MA"
        - "MZ"
        - "MM"
        - "NA"
        - "NR"
        - "NP"
        - "AN"
        - "NC"
        - "NI"
        - "NE"
        - "NG"
        - "NU"
        - "NF"
        - "MP"
        - "OM"
        - "PK"
        - "PW"
        - "PS"
        - "PA"
        - "PG"
        - "PY"
        - "PE"
        - "PH"
        - "PN"
        - "PL"
        - "PR"
        - "QA"
        - "RE"
        - "RO"
        - "RU"
        - "RW"
        - "SH"
        - "KN"
        - "LC"
        - "PM"
        - "VC"
        - "WS"
        - "SM"
        - "ST"
        - "SA"
        - "SN"
        - "RS"
        - "SC"
        - "SL"
        - "SK"
        - "SI"
        - "SB"
        - "SO"
        - "ZA"
        - "GS"
        - "LK"
        - "SD"
        - "SR"
        - "SJ"
        - "SZ"
        - "SY"
        - "TW"
        - "TJ"
        - "TZ"
        - "TH"
        - "TL"
        - "TG"
        - "TK"
        - "TO"
        - "TT"
        - "TN"
        - "TR"
        - "TM"
        - "TC"
        - "TV"
        - "UG"
        - "UA"
        - "AE"
        - "UM"
        - "UY"
        - "UZ"
        - "VU"
        - "VE"
        - "VN"
        - "VG"
        - "VI"
        - "WF"
        - "EH"
        - "YE"
        - "ZM"
        - "ZW"
    description: "User account associated with store."
